spring:
  application:
    name: service-order
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.133.103:8848
      config:
        import-check:
          enabled: false
        namespace: ${spring.profiles.active}
server:
  port: 8000

---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:datasource.properties?group=order
    activate:
      on-profile: dev
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:datasource.properties?group=order
      - nacos:test.properties?group=order
    activate:
      on-profile: test
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:datasource.properties?group=order
      - nacos:product.properties?group=order
    activate:
      on-profile: product